DEF(IR, "\tPrint IR with BB labels", {})
DEF(G, "\tPrint digraph for graphviz dot", {})
DEF(FG, "\tPrint full digraph for graphviz dot", {})
DEF(SETS, "\tPrint gen, kill, e_gen, e_kill sets for all BBs", {})
DEF(AE, "\tPrint available expressions for all BBs", {OPTION_SETS})
DEF(CSE, "\tPrint full digraph after CSE", {OPTION_AE})
